### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by vincentendrahadi** [bigpipe/diagnostics#23]
npm i @dabh/diagnostics
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@dabh%2fdiagnostics - Not found
npm ERR! 404 
npm ERR! 404  '@dabh/diagnostics@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by stockmind** [comment]
NPM partially down: https://status.npmjs.org/

**Comment by vincentendrahadi** [comment]
Ah, okay, thanks
